name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package

      - name: Create ZIP bundle
        run: |
          mkdir bundle
          cp target/*.jar bundle/app.jar
          zip -r app-bundle.zip bundle/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::329599647651:role/github-eb-deploy-role
          aws-region: eu-central-1

      - name: Upload to S3
        run: |
          aws s3 cp app-bundle.zip s3://elasticbeanapp-bundles-1/app-bundle-${{ github.sha }}.zip

      - name: Create EB Application Version
        run: |
          aws elasticbeanstalk create-application-version --application-name elasticBean-app --version-label ${{ github.sha }} --source-bundle S3Bucket="elasticbeanapp-bundles-1",S3Key="app-bundle-${{ github.sha }}.zip"

      - name: Deploy to EB Environment
        run: |
          aws elasticbeanstalk update-environment --application-name elasticBean-app --environment-name SpringCrudApp-env --version-label ${{ github.sha }}