name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java 21 (Corretto)
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build WAR package
      - name: Build WAR
        run: mvn clean package -DskipTests

      # Upload build artifact for debugging or reuse
      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-package
          path: target/*.war

      # Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: elasticBean-app
          environment_name: ElasticBean-app-env
          region: eu-central-1
          version_label: v-${{ github.run_number }}
          deployment_package: target/elasticBean-app-0.0.1-SNAPSHOT.war
